added redis sentinel support
thumbor-community/redis pull request #9
Opened 2022-04-27 22:56 UTC by RaphaelVRossi

We need to make Thumbor able to connect Redis Sentinel.

To make this possible, we created a `RedisBaseStorage` to shared common code between `Storage` and `ResultStorage`, and added a docker with Redis Sentinel to make unit tests possible.

2022-04-27 23:00 UTC, RaphaelVRossi commented
@devppjr @masom @phoet @heynemann 

Hey guys, could you review my changes please?

2022-05-04 19:29 UTC, devppjr commented
LGTM ✅ . Could you review too? @masom @heynemann @phoet @Bladrak

2022-05-04 19:35 UTC, devppjr approved these changes
LGTM ✅ . Could you review too? @masom @heynemann @phoet @Bladrak

2022-05-05 13:33 UTC, Bladrak requested changes

2022-05-05 13:33 UTC, Bladrak commented on tc_redis/base_storage.py
> +        if redis_mode == "single_node":
Might be interesting to use a switch structure to handle all possible cases. Also, I'd use a constant for the "single_node" and "sentinel" string, to avoid potential typos

2022-05-05 13:33 UTC, Bladrak commented on tc_redis/base_storage.py
> +        if redis_mode == "sentinel" and RedisBaseStorage.sentinel_storage:
Same here, a switch structure with constants could be interesting

2022-05-05 13:33 UTC, Bladrak commented on tc_redis/base_storage.py
> +        if redis_mode == "sentinel":
Here as well :)

2022-05-06 20:34 UTC, RaphaelVRossi commented on tc_redis/base_storage.py
> +        if redis_mode == "sentinel":
Changed it to Constants.

2022-05-06 21:10 UTC, RaphaelVRossi commented on tc_redis/base_storage.py
> +        if redis_mode == "single_node":
IMHO switch structure is only available on python3.10+, and we don't want to restrict only on python3.10+ versions.

Changed strings to constants.

2022-05-06 21:10 UTC, RaphaelVRossi commented on tc_redis/base_storage.py
> +        if redis_mode == "sentinel" and RedisBaseStorage.sentinel_storage:
Changed strings to constants.

2022-05-09 08:33 UTC, Bladrak commented on tc_redis/base_storage.py
> +        if redis_mode == "single_node":
Yes you're right about the switch statement. Thought it was available sooner, my bad :)

2022-05-09 08:34 UTC, Bladrak approved these changes

2022-05-09 08:34 UTC, merged

2022-05-09 13:40 UTC, devppjr commented
hi @Bladrak @masom, could u publish this [version](https://github.com/thumbor-community/redis/releases/tag/2.1.0)? Or give us permissions to publish, for me and @RaphaelVRossi? 

Users on pypi:
- devppjr
- raphaelrossi

2022-05-11 08:51 UTC, Bladrak commented
@devppjr I've sent invites from pypi, let me know if that works :-)

2022-05-11 18:58 UTC, devppjr commented
> @devppjr I've sent invites from pypi, let me know if that works :-)

thanks @Bladrak, worked finee 😊